apiVersion: apps/V1
kind: Deployment
metadata:
  name: myappnginx
  namespace: nginxnew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      app: myapp
    spec:
      containers:
        - name: nginxnewapp
          image: nginx:stable-alpine3.20-perl
          ports:
            - containerPort: 80
